name: oracle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
#-----------------------
  # ios design
  cupertino_icons: ^1.0.2
  # get atate managment
  get: 4.3.8
  # splash native
  splash_screen_view: ^3.0.0
  # flutter svg view
  flutter_svg: ^0.23.0+1
  # rating view
  flutter_rating_bar: ^4.0.0
  # get rest api
  dio: ^4.0.1
  # date time format
  intl: ^0.17.0
#-----------------
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/icons/authenticate/
    - assets/icons/bottom_nav/
    - assets/icons/components/
    - assets/icons/array/
    - assets/icons/user/
    - assets/images/user/
