name: oracle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

#-----------------------
dependencies:
  # ios design
  cupertino_icons: ^1.0.2
  # get atate managment
  get: 4.3.8
  # flutter svg view
  flutter_svg: ^0.23.0+1
  # rating view
  flutter_rating_bar: ^4.0.0
  # get rest api
  dio: ^4.0.1
  # date time format
  intl: ^0.17.0
  # form field dropDown
  select_form_field: ^2.2.0
  # image_picker:
  image_picker: ^0.8.4+4
  # exapandable text for read more:
  expandable: ^5.0.1
  # progressing_indicator:
  loading_indicator: ^3.0.2
  # url for web and telegram:
  url_launcher: ^6.0.9
  # url for whatsApp:
  whatsapp_unilink: ^2.0.0
  # cached_value:
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  # token cached
  get_storage: ^2.0.3
  # date time picker:
  flutter_cupertino_date_picker_fork: ^1.0.6
  # webview:
  webview_flutter: ^2.0.12
#-----------------

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/array/
    - assets/icons/authenticate/
    - assets/icons/bottom_nav/
    - assets/icons/components/
    - assets/icons/drawer_nav/
    - assets/icons/user/
    - assets/images/background/
    - assets/images/gameImages/
    - assets/images/user/
