name: oracle
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
#-----------------------
  # ios design
  cupertino_icons: ^1.0.2
  # get atate managment
  get: 4.3.8
  # splash native
  animated_splash_screen: ^1.1.0
#-----------------
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

